  insert into USER(USER_ID,USER_NAME,USER_TYPE,REGISTER_DATE) values (1,'USER_EMPLOYEE',1,'2017-08-10');
  insert into USER(USER_ID,USER_NAME,USER_TYPE,REGISTER_DATE) values (2,'USER_AFFILIATE',2,'2017-08-10'); 
  insert into USER(USER_ID,USER_NAME,USER_TYPE,REGISTER_DATE) values(4,'USER_NEW_CUSTOMER',3,'2017-08-10');
  insert into USER(USER_ID,USER_NAME,USER_TYPE,REGISTER_DATE) values(3,'USER_CUSER_OLD_CUSTOMER',3,'2015-08-09');